
import os
import json
from pathlib import Path

BASE_DIR = Path("c:/development/pitbula/quantivista/design/services")
INFRA_DIR = Path("c:/development/pitbula/quantivista/design/infrastructure")

def find_docs(service_dir):
    docs = []
    # Priority: overview_*.md > architecture_overview.md > README.md
    for f in service_dir.glob("overview_*.md"):
        docs.append(str(f).replace("\\", "/").replace("c:/development/pitbula/quantivista/", ""))
    
    if not docs:
        for f in service_dir.glob("architecture_*.md"):
             docs.append(str(f).replace("\\", "/").replace("c:/development/pitbula/quantivista/", ""))
             
    if not docs:
        if (service_dir / "README.md").exists():
            docs.append(str(service_dir / "README.md").replace("\\", "/").replace("c:/development/pitbula/quantivista/", ""))
            
    return docs

mapping = {}

# 1. Services
if BASE_DIR.exists():
    for item in BASE_DIR.iterdir():
        if item.is_dir():
            # Convert "market-price-service" -> "Market Price Service"
            human_name = item.name.replace("-", " ").title()
            # Handle acronyms if needed (e.g. Api -> API)
            human_name = human_name.replace("Api", "API").replace("Ui", "UI")
            
            docs = find_docs(item)
            mapping[human_name] = {
                "Type": "Service",
                "DesignRoot": str(item).replace("\\", "/").replace("c:/development/pitbula/quantivista/", ""),
                "RequiredDocs": docs
            }

# 2. Infra (Static addition based on knowns, or scan)
infra_map = {
    "Kafka Infrastructure": ["design/infrastructure/kafka.md", "design/architecture/event_catalog.md"],
    "Kubernetes Infrastructure": ["design/infrastructure/kubernetes.md", "design/infrastructure/gcp_cost_estimation.md"],
    "Terraform Infrastructure": ["design/infrastructure/terraform.md"],
    "Observability Infrastructure": ["design/infrastructure/observability.md"]
}

for name, docs in infra_map.items():
    mapping[name] = {
        "Type": "Infrastructure",
        "DesignRoot": "design/infrastructure",
        "RequiredDocs": docs
    }

# 3. Testing
mapping["End-to-End Verification"] = {
    "Type": "Testing",
    "DesignRoot": "design/roadmap/phases/phase5",
    "RequiredDocs": ["design/roadmap/phases/phase5/status.md"]
}

print(json.dumps({"_comment": "Complete Map generated by Agent", "Entities": mapping}, indent=2))
