import argparse
import sys
from pathlib import Path
import json
import logging

# Configure logging to stderr for hook compatibility (stdout might be captured)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def index_command(args):
    """
    Triggers the IngestionEngine to index the codebase.
    """
    try:
        # Use absolute imports to match package structure
        from workflow_core.knowledge.service import KnowledgeService
        from workflow_core.knowledge.ingestion.engine import IngestionEngine
        from workflow_core.knowledge.ingestion.hasher import ManifestManager

        # Load Config
        # Navigate up from this file or use CWD? CWD is safer for CLI usage in repo root.
        config_path = Path("flow_config.json").resolve()
        if not config_path.exists():
            logger.error(f"flow_config.json not found at {config_path}")
            return 1
        
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)

        # Initialize Service
        # Ensure knowledge key exists
        knowledge_config = config.get("knowledge", {})
        service = KnowledgeService(knowledge_config)
        
        # Manifest Path
        manifest_path = Path(".flow/rag_manifest.json").resolve()
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Initialize Engine
        engine = IngestionEngine(service, manifest_path)
        
        # Run Indexing
        root_path = Path(args.path).resolve()
        logger.info(f"Starting indexing for: {root_path}")
        
        # Extensions could be configurable via args or config
        engine.index_directory(root_path)
        
        logger.info("Indexing complete.")
        return 0
        
    except Exception as e:
        logger.error(f"Indexing failed: {e}", exc_info=True)
        return 1

def install_hooks_command(args):
    """
    Installs the post-commit hook.
    """
    try:
        git_dir = Path(".git")
        if not git_dir.exists():
            logger.error(".git directory not found. Must be run from repository root.")
            return 1

        hook_dir = git_dir / "hooks"
        hook_dir.mkdir(exist_ok=True)
        
        hook_path = hook_dir / "post-commit"
            
        script_content = """#!/bin/sh
# Auto-generated by Flow Knowledge System
# Trigger Knowledge Ingestion in background
echo "[Knowledge] Syncing changes to Vector Store..."

# Check if poetry exists
if command -v poetry >/dev/null 2>&1; then
    # Run in background (&) to not block the commit flow
    poetry run python -m workflow_core.knowledge.cli index src >> .flow/knowledge/ingestion.log 2>&1 &
else
    echo "[Knowledge] Error: Poetry not found. Skipping ingestion."
fi
"""
        # Note: Writing with unix line endings is crucial for bash scripts even on Windows if using Git Bash
        with open(hook_path, "w", newline='\n', encoding="utf-8") as f:
            f.write(script_content)
            
        # Make executable
        import os
        try:
            # maintain existing permissions but add execute
            st = os.stat(hook_path)
            os.chmod(hook_path, st.st_mode | 0o111)
        except Exception as e:
            logger.warning(f"Could not set executable usage: {e}")
            
        logger.info(f"Installed post-commit hook at {hook_path}")
        return 0
        
    except Exception as e:
        logger.error(f"Hook installation failed: {e}")
        return 1

def main():
    parser = argparse.ArgumentParser(description="Flow Knowledge System CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # Index Command
    index_parser = subparsers.add_parser("index", help="Index the codebase")
    index_parser.add_argument("path", nargs="?", default=".", help="Root directory to index")
    
    # Install Hooks Command
    hooks_parser = subparsers.add_parser("install-hooks", help="Install Git hooks")
    
    args = parser.parse_args()
    
    if args.command == "index":
        sys.exit(index_command(args))
    elif args.command == "install-hooks":
        sys.exit(install_hooks_command(args))

if __name__ == "__main__":
    main()
